---
- hosts: all
  tasks:
    - name: Install requirements for WiSHFUL
      become: true
      apt:
        state: present
        pkg:
        - wget
        - git
        - python3-pip

    - name: Make root dir writable
      become: true
      file:
        path: /root
        mode: "u+rwx,g+rwx,o+rwx"

    - name: Create WiSHFUL directory
      file:
        path: /root/wishful
        state: directory
        mode: "u+rwx,g+rwx,o+rwx"

    - name: Download repo file
      get_url:
        url: https://storage.googleapis.com/git-repo-downloads/repo
        dest: /root/wishful/repo

    - name: Make repo executable
      file:
        path: /root/wishful/repo
        mode: "a+x"

    - name: Init repo
      command: /root/wishful/repo init -u https://github.com/wishful-project/manifests.git
      args:
        chdir: /root/wishful/

    - name: Configure user-only manifest file
      command: /root/wishful/repo init -m user.xml
      args:
        chdir: /root/wishful/

    - name: get all repositories
      command: /root/wishful/repo sync
      args:
        chdir: /root/wishful/

    - name: create master branch on all
      command: /root/wishful/repo start master --all
      args:
        chdir: /root/wishful/

    - name: check status of all repositories
      command: /root/wishful/repo status
      args:
        chdir: /root/wishful/
        
    - name: lock matplotlib version
      become: true
      pip:
        name: "matplotlib<3.1"
        executable: pip3

    - replace:
        dest: /root/wishful/.repo/manifests/requirements.txt
        regexp: '\.'
        replace: '/root/wishful'

    - name: Install requirements
      become: true
      pip:
        requirements: /root/wishful/.repo/manifests/requirements.txt
        executable: pip3

    - name: Install module_contiki
      become: true
      pip:
        name: git+https://github.com/rmateeq/module_contiki#egg=module_contiki
        executable: pip3
