## WiSHFUL Agent config file

agent_info:
    name: 'contiki_control_agent'
    info: 'WiSHFUL example Contiki control agent'
    iface: 'eno1'

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryAgentModule
        kwargs: {"iface":eno1, "groupName":"wishful_contiki"}
    generic_connector:
        module : wishful_module_generic
        class_name : GenericConnector
        interfaces : ['lowpan0']
        kwargs :
            SupportedInterfaces : ['lowpan0']
            ControlAttributes : {"generic_connector": './protocol_connectors/generic_ctrl_attributes.csv'}
            ControlFunctions : {"generic_connector": './protocol_connectors/generic_ctrl_functions.csv'}
            ProtocolConnectors: {"generic_connector": 0}
    gitar_engine:
        module : wishful_module_gitar
        class_name : GitarEngine
        interfaces : ['lowpan0']
        kwargs : {'GitarConfig' : './config/gitar.ini','SupportedInterfaces' : ['lowpan0'],'ControlExtensions' : {'taisc' : './protocol_connectors/taisc_control_extensions.csv', 'rime' : './protocol_connectors/rime_control_extensions.csv'}}
    taisc_connector:
        module : wishful_module_taisc
        class_name : TAISCConnector
        interfaces : ['lowpan0']
        kwargs :
            RadioPrograms : {"CSMA":0,"TDMA":2,"TSCH":1}
            SupportedInterfaces : ['lowpan0']
            ControlAttributes : {'taisc_connector': './protocol_connectors/taisc_ctrl_attributes.csv'}
            ControlFunctions : {'taisc_connector': './protocol_connectors/taisc_ctrl_functions.csv'}
            ProtocolConnectors: {'taisc_connector': 3}
    rime_connector:
        module : wishful_module_rime
        class_name : RIMEConnector
        interfaces : ['lowpan0']
        kwargs :
            SupportedInterfaces : ['lowpan0']
            ControlAttributes : {'rime_connector': './protocol_connectors/rime_ctrl_attributes.csv'}
            ControlFunctions : {'rime_connector': './protocol_connectors/rime_ctrl_functions.csv'}
            ProtocolConnectors: {'rime_connector': 3}
