## WiSHFUL Agent config file

agent_info:
    name: 'contiki_control_agent'
    info: 'WiSHFUL example Contiki control agent'
    iface: 'lo'

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryAgentModule
        kwargs: {"iface":lo, "groupName":"wishful_contiki"}
    gitar_engine:
        module : wishful_module_gitar
        class_name : GitarEngine
        interfaces : ['lowpan0', 'lowpan1', 'lowpan2']
        kwargs : {'GitarConfig' : './protocol_connectors/gitar_local.ini','SupportedInterfaces' : ['lowpan0', 'lowpan1', 'lowpan2'],'ControlExtensions' : {'taisc' : './protocol_connectors/taisc_control_extensions.csv', 'rime' : './protocol_connectors/rime_control_extensions.csv'}}
    taisc_connector:
        module : wishful_module_taisc
        class_name : TAISCConnector
        interfaces : ['lowpan0', 'lowpan1', 'lowpan2']
        kwargs : {'RadioPrograms' : {"CSMA":0,"TDMA":2,"TSCH":1}, 'SupportedInterfaces' : ['lowpan0', 'lowpan1', 'lowpan2']}
    rime_connector:
        module : wishful_module_rime
        class_name : RIMEConnector
        interfaces : ['lowpan0', 'lowpan1', 'lowpan2']
        kwargs : {'SupportedInterfaces' : ['lowpan0', 'lowpan1', 'lowpan2']}

